export const PROJECT_STATUS = {
  CREATED: 'CREATED',
  SCRIPT_GENERATING: 'SCRIPT_GENERATING',
  SCRIPT_PENDING_CONFIRM: 'SCRIPT_PENDING_CONFIRM',
  SCRIPT_CONFIRMED: 'SCRIPT_CONFIRMED',
  VIDEO_GENERATING: 'VIDEO_GENERATING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
} as const;

export type ProjectStatus = (typeof PROJECT_STATUS)[keyof typeof PROJECT_STATUS];
